---
spring:
  application:
    name: spring-cloud-eureka
  profiles: eureka1
server:
  port: 8000
eureka:
  instance:
    hostname: eureka1
  client:
    serviceUrl:
      defaultZone: http://eureka2:8001/eureka/,http://eureka3:8002/eureka/
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: eureka2
server:
  port: 8001
eureka:
  instance:
    hostname: eureka2
  client:
    serviceUrl:
      defaultZone: http://eureka1:8000/eureka/,http://eureka3:8002/eureka/
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: eureka3
server:
  port: 8002
eureka:
  instance:
    hostname: eureka3
  client:
    serviceUrl:
      defaultZone: http://eureka1:8000/eureka/,http://eureka2:8001/eureka/